export const MapLabels = {
  "US-AL": "Alabama LLC",
  "US-AK": "Alaska LLC",
  "US-AZ": "Arizona LLC",
  "US-AR": "Arkansas LLC",
  "US-CA": "California LLC",
  "US-CO": "Colorado LLC",
  "US-CT": "Connecticut LLC",
  "US-DE": "Delaware LLC",
  "US-FL": "Florida LLC",
  "US-GA": "Georgia LLC",
  "US-HI": "Hawaii LLC",
  "US-ID": "Idaho LLC",
  "US-IL": "Illinois LLC",
  "US-IN": "Indiana LLC",
  "US-IA": "Iowa LLC",
  "US-KS": "Kansas LLC",
  "US-KY": "Kentucky[E] LLC",
  "US-LA": "Louisiana LLC",
  "US-ME": "Maine LLC",
  "US-MD": "Maryland LLC",
  "US-MA": "Massachusetts[E] LLC",
  "US-MI": "Michigan LLC",
  "US-MN": "Minnesota LLC",
  "US-MS": "Mississippi LLC",
  "US-MO": "Missouri LLC",
  "US-MT": "Montana LLC",
  "US-NE": "Nebraska LLC",
  "US-NV": "Nevada LLC",
  "US-NH": "New Hampshire LLC",
  "US-NJ": "New Jersey LLC",
  "US-NM": "New Mexico LLC",
  "US-NY": "New York LLC",
  "US-NC": "North Carolina LLC",
  "US-ND": "North Dakota LLC",
  "US-OH": "Ohio LLC",
  "US-OK": "Oklahoma LLC",
  "US-OR": "Oregon LLC",
  "US-PA": "Pennsylvania LLC",
  "US-RI": "Rhode Island LLC",
  "US-SC": "South Carolina LLC",
  "US-SD": "South Dakota LLC",
  "US-TN": "Tennessee LLC",
  "US-TX": "Texas LLC",
  "US-UT": "Utah LLC",
  "US-VT": "Vermont LLC",
  "US-VA": "Virginia LLC",
  "US-WA": "Washington LLC",
  "US-WV": "West Virginia LLC",
  "US-WI": "Wisconsin LLC",
  "US-WY": "Wyoming LLC",
};
