version: "3.7"
services:
  gatsby:
    container_name: gatsby
    image: gatsbyjs/gatsby
    build: .
    working_dir: /source
    environment:
      GATSBY_ACTIVE_ENV: staging
    entrypoint: ["gatsby", "serve", "--port", "80", "--host", "0.0.0.0"]
    network_mode: host
