version: "3.7"
services:
  gatsby:
    container_name: gatsby
    image: gatsbyjs/gatsby
    build:
      context: .
      args:
        GATSBY_ACTIVE_ENV: staging
    working_dir: /source
    environment:
      GATSBY_ACTIVE_ENV: staging
    entrypoint: ["GATSBY_ACTIVE_ENV=staging", "gatsby", "serve", "--port", "80", "--host", "0.0.0.0"]
    network_mode: host
